spring.application.name=SpringSegurity

spring.datasource.url=jdbc:mysql://localhost:3306/banca_digital?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=mi_super_secret_key_123456
jwt.expiration=900000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuemail@gmail.com
spring.mail.password=tu-password-app

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true